version: '3.8'
services:
  nubit-light:
    build: .
    ports:
      - "18081:8080"
    environment:
      - NUBIT_NAME=${NUBIT_NAME}
      - NUBIT_GAS_COUPON=${NUBIT_GAS_COUPON}
    command: /data/modular-indexer-light/run.sh

